services:
  search.index.storage:
    class: Vainyl\Search\Storage\IndexStorage
    arguments: ['@map.prototype']
  search.index.composite:
    class: Vainyl\Search\Composite\CompositeIndex
    arguments: ['@search.index.storage']
  search.index: '@search.index.composite'
  search.index.abstract:
    abstract: true
    class: Vainyl\Search\AbstractIndex
    arguments: ['@domain.storage']
  domain.metadata.factory.search:
    decorates: domain.metadata.factory
    class: Vainyl\Search\Domain\Decorator\SearchDomainMetadataFactoryDecorator
    arguments: ['@domain.metadata.factory.search.inner']